# Copyright (c) 2025 ByteDance Ltd. and/or its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import argparse
import os.path as osp

from extract_post_condition import EGraph

parser = argparse.ArgumentParser(description="E-Graph Visualization")

parser.add_argument(
    "-i",
    "--input_path",
    type=str,
    help="JSON file generated by Egger.",
)
args = parser.parse_args()

egraph = EGraph(args.input_path)
egraph.visualize_saturated()
